### ISSUE TITLE
cli+ hangs in Windows 10

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#103]
cli+ hangs when run on Node 10 from command.exe.

It works when run from mintty (though setting prompts is awkward). Its reported cli+ works when run on Node 8 from command.exe (awaiting final confirmation). (Now confirmed.)

The problem has been tracked down to a yeoman issue. Yeoman uses queues to schedule its tasks. The prompt task for `generate app`  runs and ends properly. The writing task, which yeoman automatically queues to run thereafter, never starts.

**Comment by eddyystop** [comment]
Valuable info. Thanks.

**Comment by eddyystop** [comment]
https://github.com/yeoman/generator/issues/1098

**Comment by eddyystop** [comment]
Well no respone from yeoman for 6 days.

Published cli+ v0.7.66 which runs generator v0.6.64. I expect it to avoid hangs in command.exe and PowerShell for `generate app` ONLY.

This change runs against the grain of yeoman design. Could you all please run `generate app` to see if there are unintended side effects. Also please run `npm start` after generation.

I'll propagate the changes to the other `generate` once we are comfortable `app` works.

**Comment by eddyystop** [comment]
@pkej Are you willing to run this test? Thanks in advance.

**Comment by evaera** [comment]
I just encountered this today on Windows 10 in PowerShell, cmd.exe, *and* bash shell. It always hung after:

- `Data mutating tests and seeding may run when NODE_ENV is one of (optional)` step if I hit enter without entering anything
- If I enter something, it hangs after the next step (`Seed data records`).

This was finally enough for me to get around to installing WSL on my machine and it worked once inside there.

**Comment by eddyystop** [comment]
Thanks for the info about Git Bash.

I've avoided WSL because I wanted to avoid incompatibilities and short comings, i.e. traditional MS issues. Please let me know your experience.

**Comment by NickBolles** [comment]
Weirdly, I haven't seen any issues running from local dev on Window 10
Windows 10 version - 10.0.17134 Build 17134
node - 10.11.0 
@feathers-plus/cli - 0.7.73
Master branch head of generator

**Comment by eddyystop** [comment]
Could everyone having issues please provide their windows build number. Windows 10 automatically updates pcs

**Comment by evaera** [comment]
Windows - 10.0.17134
Node - 11.4.0 (Also tested with 10.x with no luck)
Feathers-plus version - 0.7.73

**Comment by eddyystop** [comment]
Info thanks

**Comment by tmcmah1** [comment]
Windows - 10.0.10586
Node - 11.6.0
Feathers-plus - 0.7.74

**Comment by eddyystop** [comment]
info thanks.

**Comment by eddyystop** [comment]
There may have been movement on this issue from Strapi https://github.com/strapi/strapi/pull/2565 .

Could someone experienmcing this hang try the following:
- Remove node_modules/inquirer
- `npm i -d inquirer`

This will replace inquier 6.2.0 with 6.2.1

@pkej @evaera @tmcmah1 ^^^

**Comment by eddyystop** [comment]
Info thanks.

**Comment by Hobbs1210** [comment]
i ran into this issue after upgrading Node JS from 9.9 to 11.7 on windows 10

**Comment by brane53** [comment]
I'm having the same issue. I tried doing a local install of inquirer as described above, but it did not work. Also, may be worth pointing out I was on Win 10 Home (Version 1803) about a week ago and I had no issues with the cli hanging at the end of the prompts. I just updated to the latest October update Win 10 Home (1809) and now I'm experiencing the cli hanging. Everything else is the same

Win 10 Home (1809)
Nodejs 10.15.0
feathers-plus cli 0.7.75

**Comment by delebash** [comment]
Same here.
Windows Professional x64
Version 10.0.17763 Build 17763
Nodejs 11.6.0
feathers-plus cli 0.7.75

**Comment by eddyystop** [comment]
Its seem appropriate to once again explain what is happening.

Cli+ makes no calls to the terminal or the file system directly. It uses yeoman for that.

This issue us buried somewhere in yeoman code but yeoman's maintainer doesn't seem interested despite multiple pokes from me.

**Comment by eddyystop** [comment]
Here is the issue I posted at yeoman https://github.com/yeoman/generator/issues/1098

This seems to be the latest suspect for the cause https://github.com/SBoudrias/Inquirer.js/issues/767

**Comment by tmcmah1** [comment]
Another Windows 10 workaround for now, if you can't or don't wish to install WSL, is to install [nvm-windows](https://github.com/coreybutler/nvm-windows).  Note: This project is specific to Windows, not the nvm project for Mac/Linux.

This allows me to use node 8.x for my feathers-plus projects, and easily switch to other versions of node, if necessary, with the '[nvm use](https://github.com/coreybutler/nvm-windows#user-content-usage)' command. 

Windows - 10.0.10586
Node - 8.15.0
Feathers-plus - 0.7.76

@eddyystop Thanks for all your continued hard work on the feathers project!  It is greatly appreciated!

**Comment by Clarence-L** [comment]
Hangs in WIndows 10.0 and 8.1 both using node 10.15.3 from cmd and powershell terminals.

I was able to run the generator from an emacs shell, unfortunately I wasn't able to change the options on subsequent generator calls because the arrow and spacebar inputs just moved the curser and entered spaces and did't set the options. Something to do with (n)curses I believe.

If I could find a way to edit the options in emacs shell, I would be happy with that but my project must be in node 10.15.3 LTS.

**Comment by Clarence-L** [comment]
Found a solution using [http://cygwin.com/](url)

From the cygiwin terminal:
$ mintty

This will open the mintty terminal. From there navigate to the feathers-plus project directory and run the generator.

The arrow and spacebar inputs are not reflected in the terminal but they do register and are confirmed on enter.
![mintty](https://user-images.githubusercontent.com/17663647/55113030-72b04200-50b4-11e9-876b-83f8f956e394.png)

**Comment by bisubus** [comment]
The problem is specific to Node 10+ and Windows in general. I published a set of Node executable wrappers to use specific Node version together with global Node in the same project, specifically `@ex-machine/node8`. It can be used to run entry script of a generator:

```
node8 ./node_modules/@feathers-plus/cli/lib/index.js
```
