### ISSUE TITLE
[improvement] Update resolvers in service.populate.js

### ISSUE THREAD

**Issue by marshallswain** [feathers-plus/generator-feathers-plus#106]
In `service-name.populate.js`, for this line: 

```
const resolvers = require('../../../services/graphql/service.resolvers')
```

When Batch Loaders are selected for the graphql generation, we can update it to use the batchloader.resolvers, like this:

```
const resolvers = require('../../../services/graphql/batchloader.resolvers')
```

**Comment by marshallswain** [comment]
The only reason I have is that If I started out by generating the app to use `batchLoaders.resolvers`, I would expect the generator to use them, then I would expect to manually override the others.  It wouldn't make sense for me to tell the generator to use `batchloader.resolvers` and it then requires me to go override all of the populate imports to override the use of the `service.resolvers`.

**Comment by eddyystop** [comment]
`generate graphql` is concerned about generating the GraphQL endpoint. You tell the generator which resolvers you want to use for the GraphQL endpoint.

I understand your issue but I feel having that prompt apply to both the endpoint and fgraphql is overloading it. Need to think on this.
