### ISSUE TITLE
Make code list more user-friendly

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/generator-feathers-plus#145]
I think there are a lot more higher priority, and higher impact issues right now, so treat this as a future idea.

It would be cool if we could output a little web page with the code changes that you've made. Right now it spits out a ton of console output, that I find unreadable. But I'm really interested in how much of my code is actually different from the generator

A few Ideas

- Determine a standard output for the code blocks (json Array? maybe a JSON array of jsDiff objects?)
- Diff the actual code instead of the whole code block. This could help identify places that don't need to be modified (such as a whitespace change or something)
- Some stats would be cool too

**Comment by eddyystop** [comment]
The output of `generate codelist` is primarily intended to be the contents of the feathers-gen-code.js file as described in https://medium.com/@eddyystop/create-your-own-super-scaffolding-automatically-add-custom-code-89418e888dac .
