### ISSUE TITLE
Running `feathers-plus generate app` doesn't generate authentication

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/generator-feathers-plus#150]
This is a little bit of weird one. But if you generate, say the ts-cumulative-1-generic.test-copy (copy that folder into a new temp folder and run `feathers-plus generate app`) the authentication portion isn't generated. you need to run `feathers-plus generate authentication` after `app`

**Comment by eddyystop** [comment]
You sure? Generate authentication us always run on generate all.

**Comment by NickBolles** [comment]
Maybe this is intended. I think `app` is supposed to be more of an init, but it seems like it should do the same as `all`, which does correctly add authentication if it's in the specs

**Comment by eddyystop** [comment]
I'm not near a device. Generate all defonately dies generate authentication or most of the expansion tests would fail.

**Comment by eddyystop** [comment]
Generate app generates the same modules as the feathersjs/app. You have to run generate all to regenerate everything.

**Comment by NickBolles** [comment]
Perfect. Then it's working as expected. My bad.
