### ISSUE TITLE
Add code block to define custom CORS configuration

### ISSUE THREAD

**Issue by franfran3** [feathers-plus/generator-feathers-plus#159]
It would be nice to add in src/app.?s a code block to allow custom CORS configuration:

```javascript
app.use(cors(
  // !code: cors_config // !end
));
```

**Comment by eddyystop** [comment]
Resolved via https://github.com/feathers-plus/generator-feathers-plus/pull/160 .

Published as cli+ 0.7.75 using generator v0.6.73.
