### ISSUE TITLE
Format generated code

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/generator-feathers-plus#164]
## The Problem
Overall I think formatting of the code is one of the biggest challenges facing CLI+. If you use a different quote style or line ending style, regenerating with CLI+ makes all of your code deviate from that style (in certain cases)

If we could generate the code and format it based on the user's workspace, I think it would be a gigantic win for CLI+

### Examples
I was using " instead of ' (or vice versa, I forget) and LF as line ending. But CLI+ generates the files with the opposite quote and with CRLF (since I'm on windows). 

### Other examples

- Line endings
- Quote style
- Semicolons (this is currently an option for CLI+, but could be removed completely, which would have the added benefit of simplifying templates)
- Testing
  - My biggest hesitation to make changes to CLI+ (esp Typescript cahnges) is because it will break the tests, which takes a lot of careful find/replace to fix. 
  - Over half of the time (in my experience) this has been caused by a whitespace issue, or a semicolon, or new line ending issue, aka annoying formatting issues.
  - Formatting the code (both the expected code and generated code) could completely eliminate this issue I think, or at least the annoying formatting issues

## Solution?
If we could run the code through prettier or something when we write it, and take into account the users .prettierrc (or whatever config), I think we could resolve all of the issues under `other examples`. Maybe this could be a plugin type system so that it could use any formatter.

**Comment by eddyystop** [comment]
I suggest users create a script which runs the generator and then their linter.

**Comment by NickBolles** [comment]
@eddyystop right, that's one way to tackle this, but it's an extremely common use case. Do you think this would be useful to have built into CLI+? It might even just be a transform for yeoman, which could utilize existing Gulp plugins I believe.

https://yeoman.io/authoring/file-system.html#transform-output-files-through-streams

**Comment by eddyystop** [comment]
Unix design is small pieces of code each doing one thing, which feed one into the other. I would rather cli+ not worry about style as its purpose is to write code.

**Comment by NickBolles** [comment]
I 100% agree that modularity is a critical piece of software design. I work at a large software company and one of the major failures I see in previous code is lack of modularity and encapsulation. It results in tons of DRY code and slower implementation. That being said, another big issue is not doing things at a low enough level. If it's not done at the correct level of abstraction then it will negatively impact a larger group implementing that layer of abstraction. It results in a lack of modularity and results in more, and lower quality DRY code.

To put that into CLI+ terms, if we don't implement something (in this case formatting) then it will just be one more thing to do by the user, and the chances of users doing it wrong, or having issues is much higher. It's already CLI+s goal to generate code and abstract that maintenance. Why not linting too?

Sure, it's fairly easy to implement a linting script, but my guess is 95% of users will want to format the code, the only exception being those that have the exact same style as CLI+, or just go with CLI+'s config. I think that's unnecessarily restrictive. Especially when you have client and server code in the same repo.

I think we should just add a way to add transforms on file write, which could utilize any file stream and gulps existing infrastructure. For example I think every one of the plugins listed under [linting on Awesome-gulp](https://github.com/alferov/awesome-gulp#linting) could be just plugged in, with the right config.
