### ISSUE TITLE
SQL Syntax error with Sequelize, TS and MySQL 8 ?

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#169]
This is issue in feathers-plus/cli remain open: https://github.com/feathers-plus/cli/issues/26 . That also refers to https://github.com/feathers-plus/cli/issues/27 .

**Comment by eddyystop** [comment]
@j2L4e ^^^

**Comment by GhuronZhan** [comment]
Hello,
Thank for your help... i'm really stuck and don't understand all these interlocked TS issues...
NB: sorry, for the post on /cli and not here, i followed the nearest link to the documentation ^^'

**Comment by lukeburpee** [comment]
@eddyystop @NickBolles @GhuronZhan @j2L4e  just created a pull request with the fix for this issue
see #171

**Comment by NickBolles** [comment]
Is this fixed now?

**Comment by eddyystop** [comment]
Thanks for another catch. Published as f+/cli v0.7.79 using generator v0.6.77
