### ISSUE TITLE
generator keeps restoring @types/winston even if deleted manually from package.json

### ISSUE THREAD

**Issue by blackholegalaxy** [feathers-plus/generator-feathers-plus#196]
### Steps to reproduce

 - Remove `@types/winston` from dev dependencies in `package.json`
 - Use `feathers-plus generate all`

### Expected behavior
- The generator should not add any manually deleted package or should provide a way to exclude packages

- For this specific case, `@types/winston` should be removed completely from generator since it's marked as unecessary by package authors as typing is included in `winston` package

### Actual behavior
The generator put back `@types/windston` in dev dependencies and install it.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-plus 0.7.80

**NodeJS version**:
v8.15.0 and 10.x

**Operating System**:

osX mojave and windows 10 pro

**Comment by eddyystop** [comment]
Based on your comment about typings being included within the winston repo, I think the proper thing to do is never include @typings/winston.

Do you see any issues with this?

**Comment by blackholegalaxy** [comment]
Nope as I said, its marked as useless by winston itself :) so I think it's safe to remove it from generator dependencies pool.
