### ISSUE TITLE
add an option to generate a data-less service without db and schema files

### ISSUE THREAD

**Issue by blackholegalaxy** [feathers-plus/generator-feathers-plus#197]
### Suggestion context

We try to define some services which are required to access `app` context and which are able to use hooks. But these services are not data related. For example: defining a `healthCheck` service which will check third party micro-services (including mongo) are available.

This service will not contain data business logic but only http request to some external services or feathers configuration reading, or write files without the need to store or read anything from a data storage.

### Current behavior
When generating the service, we chose `custom service`. But the generator keeps asking us to create a schema file then tries to generate an interface file (we are in a typescript project) and mongoose/graphQL/postgre files.

### Expected behavior
We would like a CLI option on `generate service` to be able to tell generator this service is generic/data-less. Then on `generate all` we'll then expect the generator not to regenerate the data related files.

**Comment by eddyystop** [comment]
You can create custom services by manually adding custom code in the various code insertion points.

We have been thinking of the cleanest way to add non database services e.g. feathers-twilio. An "empty" service would fit in this category.

**Comment by blackholegalaxy** [comment]
I added custom code in the insertion points. But feathers-plus cli keep generating schema and mongoose / postgre / graphql files. The class is not the problem and works properly. We just don't want the CLI to regenerate data files.

**Comment by eddyystop** [comment]
You need to delete your custom service from module feathers-gen-specs.json property services.

**Comment by blackholegalaxy** [comment]
Basically yes we can create custom non-database service by hand or create it by CLI, making some cleanup then removing fron feathers-gen-specs.json. 

But my suggestion/ask for feature is about allowing it to be created and maintained through CLI. But it requires some more option in the CLI and feathers-plus to support this kind of service.

**Comment by eddyystop** [comment]
Your comments are noted. Such services are closer to the utility services I mentioned than to the database ones and would be supported there.

Use custom code in the meantime.

**Comment by blackholegalaxy** [comment]
Glad to here it's in the plans :) Utility service will for sure suit this need :)
