### ISSUE TITLE
Sequelize array type instead of jsonb

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/generator-feathers-plus#216]
### Expected behavior

when using { type: 'array', items: { type: 'string' } } as a property in schema.js file
the generator should generate 
type: DataTypes.ARRAY(DataTypes.TEXT) for sequelize model

### Actual behavior

it generates 
type: DataTypes.JSONB

**Comment by eddyystop** [comment]
cli+ uses https://github.com/ronalddddd/sequelizer/blob/master/lib/JsonSchemaDefinition.js to convert a JSON-schema to a Sequelize model, and that converts arrays to DataType.JSONB.

I don't see how we can change that without forking sequelizer. That is not something I'm eager to consider until I see multiple issues posted on this.

For now you'll have to override the DataType.JSONB in serviceName.sequelize.?s with custom code at `// !code: moduleExports // !end`.

**Comment by eddyystop** [comment]
Note to self: Perhaps the main (only?) advantage of `ARRAY( TEXT )` vs JSON[B] is the type checking at the db level. If the JSON-schema is used to validate an array of text, that may be almost as good.

**Comment by eddyystop** [comment]
Note to self: DataTypes.ARRAY is only available in Postgres. Implementing DataTypes.ARRAY could not be generic.

**Comment by MohammedFaragallah** [comment]
Thank you I do override serviceName.sequelize.?s and it works, great work.
