### ISSUE TITLE
sequelize  defaultValue instead of default

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/generator-feathers-plus#217]
**when using default attribute in the schema**

`number: { type: 'integer', default: 0 }`

**then regenerate it outputs this in sequelize model**

visual: { type: DataTypes.INTEGER,      **default**: 0    }

**but it should outputs this to work with sequelize**

 visual: { type: DataTypes.INTEGER, **defaultValue**: 0 }

i think sequelize defaultValue only work with postgres

**Comment by eddyystop** [comment]
Resolved by https://github.com/feathers-plus/generator-feathers-plus/pull/219

**Comment by eddyystop** [comment]
Published as cli+ 0.8.1 which uses generator 0.8.1.

**Comment by MohammedFaragallah** [comment]
Thank you, great work.
