### ISSUE TITLE
Mal formed ts code

### ISSUE THREAD

**Issue by grbspltt** [feathers-plus/generator-feathers-plus#224]
### Steps to reproduce
 feathers-plus/cli to 0.8.2
Using node 8.15.0 64 bit
NPM 6.8.0
I did not install sequelize from the CLI.
The exact commands I ran from this latest test after upgrading
feathers-plus generate options
TypeScript - Y
Semicolons - Y
Module Changes - N
feathers-plus generate app
** select default options **
Use NPM
feathers-plus generate authentication
Username & Password
Sequelize
GraphQL
SQL Server
I added the JSON schema and ran
feathers-plus generate all

### Expected behavior
`sequelize-mssql.ts` should have properly formed code.
Line 47 `export default function (app: App) {…`

Line 72 `app.setup = function (...args: any[]) {`

### Actual behavior
Missing open parenthesis before `app:` :
`export default function app: App) {…`

Extra opening curly bracket after function ()
`app.setup = function (...args: any[]) {{`

Found the errors here:
https://github.com/feathers-plus/generator-feathers-plus/blob/master/generators/writing/templates/src/_adapters/sequelize-mssql.ejs#L47
https://github.com/feathers-plus/generator-feathers-plus/blob/master/generators/writing/templates/src/_adapters/sequelize-mssql.ejs#L72

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
8.15.0 64 bit
**Operating System**:
WIndows 10
**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by eddyystop** [comment]
Resolved by https://github.com/feathers-plus/generator-feathers-plus/pull/225

**Comment by eddyystop** [comment]
Published as cli+ 0.8.3 which runs generator v0.8.3
