### ISSUE TITLE
Discussion: if we should be able to have multiple separated feathers-gen-specs

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/generator-feathers-plus#227]
I've I small sized project with less than 20 services with one hook for some of them and feathers-gen-specs.json is already more than 400 lines.
what do you think about making it in multiple files!
example: one for services another for hooks another for the app options etc.

**Comment by NickBolles** [comment]
@MohammedFaragallah why does it matter how long it is? It's rarely touched manually. 

It would be interesting to allow JavaScript usage, which could mean splitting it up or generating the specs via code. ( `For service in service names return service specs descriptor`)

**Comment by MohammedFaragallah** [comment]
I can't think of very common use cases right now but for me, I modify it frequently.

**Comment by eddyystop** [comment]
First, congratulations for manually mutating feathers-gen-specs.json. It speaks to you competence with cli+.

cli+ is complicated and I don't think its a good idea to make it more complicated just to ease editing of feathers-gen-specs.json. Think of the issues that could arise its potential constituent parts got out of sync.

**Comment by MohammedFaragallah** [comment]
Thanks for the explaination @eddyystop you are absolutely right.
