### ISSUE TITLE
GgraphQL NO SCHEMA AVAILABLE

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/generator-feathers-plus#229]
I'm very new to GraphQL but as suggested in [this article](https://medium.com/@mattchewone/graphql-with-feathersjs-4cc67e785bd) I'm trying [graphiql](https://medium.com/@mattchewone/graphql-with-feathersjs-4cc67e785bd) 

everything is working but I get NO SCHEMA AVAILABLE

![graphiql_2019-02-25_02-09-47](https://user-images.githubusercontent.com/14910456/53307595-bd1a8500-38a2-11e9-8c6d-c50e2822478a.png)

any idea how to fix that or what I'm doing wrong.
sorry if it's not related after a lot of searching I didn't know where to ask

**Comment by eddyystop** [comment]
I don't. Perhaps you can PM "Matt" on Feathers Slack.

**Comment by MohammedFaragallah** [comment]
I did talk to "Matt" same result with him then tried graphiql component same issue I think feathers-plus generated graphql service doesn't allow docs schema by default I'll try to get more info and come back to you

**Comment by eddyystop** [comment]
You issue was not with anything in Matt's article. You are asking for the generated GraphQL code to support introspection. That is not a priority for us at this time.

I don't believe there is anthing preventing you from adding custom code to services/graphql/* which implements introspection.

**Comment by MohammedFaragallah** [comment]
I didn't know that schema introspection is a separate thing, sorry about that.
