### ISSUE TITLE
How to manage complex schema database with JSON Schema

### ISSUE THREAD

**Issue by superdevofficial** [feathers-plus/generator-feathers-plus#237]
When I export a service, I can't export complex schema information into Sequelize or Mongoose schema.  Example : relationship information or constraint are ignored, so Sequelize and Mongoose are missing some parameters.

Here I submit a PR to solve a part of this issue for Mongoose : #236 
**BUT** I'm not sure is good solution, so guys, **how do you manage this kind of problem ?**
There is an example project with complex database schema ?

### Steps to reproduce

If you need a relationship like this:
```js
let schema = {
//...  
  properties: {
    //foreign key or ref to another model in order to join or populate
    parentId:  { type: 'ID', ref: 'User' },
  }
}
```

### Expected behavior

You expect something like this :
```js
//sequelize
parent_id: {
   type: Sequelize.INTEGER,
   references: {
     model: User,
     key: 'id',
     deferrable: Sequelize.Deferrable.INITIALLY_IMMEDIATE
   }

//or mongoose
parentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User"
    },
```

### Actual behavior

But actually you get :
```js
//sequelize
parentId: {
      type: DataTypes.INTEGER
    },
//mongoose
parentId:  mongoose.Schema.Types.ObjectId,
```

### System configuration

**Module versions** (especially the part that's not working):
0.8.3
**NodeJS version**:
v10

**Comment by eddyystop** [comment]
You can add to or overwrite the generated Mongoose schema with a custom object in serviceName.mongoose.?s at `// !code: moduleExports // !end`
