### ISSUE TITLE
Generator breaking when adding project sub-directories with node_modules

### ISSUE THREAD

**Issue by joaopramos** [feathers-plus/generator-feathers-plus#24]
### Steps to reproduce
Hello,
I've been playing around with the generator-feathers-plus and noticed that the generator started breaking after adding the frontend client/ directory.

To reproduce, simply run:
1. ```npx create-react-app client``` 
2. ```cd client && npm install```
3. ```cd .. && feathers-plus generate all```

From line 45 in code-fragments.js:
```${destinationRoot}/**/*.{js,ts}`, { ignore: `${destinationRoot}/node_modules/**` }```
We can see that the node_modules directory are not being ignored for subdirectories,
Changing this line to:
```${destinationRoot}/**/*.{js,ts}`, { ignore: `${destinationRoot}/**/node_modules/**` }```
resolved the issue for me

### Expected behavior
The generator should run the prompts

### Actual behavior
The generator exits with an error:
```
Using generator version 0.2.24
{ Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at fs.readFileSync (fs.js:583:19)
    at extractFiles (/Users/joao/.nvm/versions/node/v8.9.0/lib/node_modules/@feathers-plus/cli/node_modules/@feathers-plus/generator-feathers-plus/lib/code-fragments.js:64:25)
```

### System configuration

**NodeJS version**:
v8.9.0

**Operating System**:
macOS

**Comment by eddyystop** [comment]
Fixed via https://github.com/feathers-plus/generator-feathers-plus/pull/25

**Comment by eddyystop** [comment]
Published as f+/cli v.0.4.19 running generator v0.2.25.
