### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/generator-feathers-plus#240]
According to #164, the recommendation for formatting is to run a linter with `--fix`

Since most linters have semicolon fixers, why do we we been include semicolons at all in any of the generator? It seems like it just makes things more complex and confusing. We could just remove then completely and leave it to the linter to fix them. The linters also offer a lot more flexibility with respect to code format. So that seems like the right decision to me.

**Comment by eddyystop** [comment]
Nowhere does it say you have to run a linter as the generated code satisfies the linting used by Feathersjs modules. You can run a linter if you want to follow other standards.

As a practical matter, no one is going to spend more than a day removing the `<%- sc %>` from the templates, only to require people who haven't needed a linter before to start using one.
