### ISSUE TITLE
NPM start:seed script for TypeScript Node

### ISSUE THREAD

**Issue by deskoh** [feathers-plus/generator-feathers-plus#242]
### Steps to reproduce

- [x] Tell us what broke. The more detailed the better.
 
The generated `start:seed` script when TypeScript is used does not work.

```sh
cross-env NODE_ENV=test ts-node --seed --files src/
```

### Expected behavior
Database should be seeded with fake data.

The following NPM script fixes the issue:

```sh
cross-env NODE_ENV=test ts-node --files src/ --seed"
```

### Actual behavior
Database is not seeded with fake data `seed` argument is not passed to node. i.e. `process.argv = ['node', 'D:\code\feathers-ts\src']`.

### System configuration
Windows
TypeScript

**Comment by eddyystop** [comment]
Resolved by PR https://github.com/feathers-plus/generator-feathers-plus/pull/244

Published as f+/cli 0.8.7 which uses generator v0.8.7
