### ISSUE TITLE
Migration from TSLint to ESLint

### ISSUE THREAD

**Issue by deskoh** [feathers-plus/generator-feathers-plus#250]
### Migration to ESLint

TSLint will soon deprecated. See https://github.com/palantir/tslint/issues/4534 and
https://github.com/Microsoft/TypeScript/issues/29288.

Any current plan to transit to ESLint?

A recent [guide](https://dev.to/robertcoopercode/using-eslint-and-prettier-in-a-typescript-project-53jb) on using ESLint for TS files.

**Comment by eddyystop** [comment]
The announcement says the tslint team will work to upgrade eslint. That'll take a while.

Cli+ will make the change when it's time if the ts maintainers address it.
