### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by Heartnett** [feathers-plus/generator-feathers-plus#253]
Please update the changelog.

**Comment by eddyystop** [comment]
The changelog would just list the commits. You can look at the commits directly.

**Comment by Heartnett** [comment]
@eddyystop Thanks for the reply. Please know that not everyone has the time to go through the commits one-by-one.

**Comment by eddyystop** [comment]
Please understand I could be making over $100/hr instead of saving you some time for free.

**Comment by Heartnett** [comment]
> 
> 
> Please understand I could be making over $100/hr instead of saving you some time for free.

Don't get me wrong, I appreciate the work done on this project! Could the changelog process not be automated somehow? Also this won't benefit just me.

**Comment by eddyystop** [comment]
Many Open Source contributors consider the OS model to be broken. The *mildest* article concerning this could be https://motherboard.vice.com/en_us/article/43zak3/the-internet-was-built-on-the-free-labor-of-open-source-developers-is-that-sustainable . You can find other articles.

This should help put your request in context.

**Comment by Heartnett** [comment]
Noted, thanks.
