### ISSUE TITLE
Add support for graphql mutations

### ISSUE THREAD

**Issue by iamgmd** [feathers-plus/generator-feathers-plus#260]
Currently when generating a graphql endpoint, only get and find queries are generated. Could support be added for mutations so that CRUD could be achieved through graphql or is it part of the design to always add mutations manually into the resolvers?

**Comment by eddyystop** [comment]
This would be a LOT of work and not in the immediate plans.

The idea is to add mutations and subscriptions as manual code. Code insertion points for these exist throughout.
