### ISSUE TITLE
How do you define associations in the json schema file?

### ISSUE THREAD

**Issue by delebash** [feathers-plus/generator-feathers-plus#268]
Given a User schema and a Role schema where users have many roles how do you define this relationship in the schema file.  I see that you can do this using faker but if I am just defining the relationship and was not using faker how do I represent this relationship the schema.   The purpose of this would be able to run a feathers query to get a users role.

Database is mysql

Thanks.

**Comment by MarcGodard** [comment]
Are you using graphql? https://generator.feathers-plus.com/guide/#graphql

If not, its not needed in the schema unless I am not understanding something?

If you are just looking to store relationship IDs, you can do that in the Schema then use something like [fastjoin](https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#fastJoin) in your hook to connect the data.

**Comment by delebash** [comment]
Fastjoin will work for me.  Thank you very much.
