### ISSUE TITLE
Can't compile Typescript

### ISSUE THREAD

**Issue by Navino16** [feathers-plus/generator-feathers-plus#276]
Hello, I can't run any featherjs project in Typescript

### Steps to reproduce
- Create new directory, for exemple directory named "test"
- Run feathers-plus generate options
![image](https://user-images.githubusercontent.com/22234867/59263722-32ed0580-8c74-11e9-9617-543a8d51e5a3.png)
- Run feathers-plus generate app
![image](https://user-images.githubusercontent.com/22234867/59263794-587a0f00-8c74-11e9-8c5f-c30b2705a95a.png)
- Run npm run tslint
- Run npm run compile

### Expected behavior
Successfull compile without any error.

### Actual behavior
Compile crash :
`src/app.ts(76,15): error TS2345: Argument of type '(app: Application<{}>) => void' is not assignable to parameter of type '(this: Application<any>, app: Application<any>) => void'.
  Types of parameters 'app' and 'app' are incompatible.
    Type 'Application<any>' is missing the following properties from type 'Application<{}>': search, connect, init, defaultConfiguration, and 39 more.`
![image](https://user-images.githubusercontent.com/22234867/59263982-bc9cd300-8c74-11e9-9257-46e2c32992be.png)

Note that adding a service generate (with default options) this error:
`src/services/index.ts(11,17): error TS2345: Argument of type '(app: Application<{ 'messages': Message; }>) => void' is not assignable to parameter of type '(this: Application<{ 'messages': Message; }>, app: Application<{ 'messages': Message; }>) => void'.
  Types of parameters 'app' and 'app' are incompatible.
    Type 'Application<{ 'messages': Message; }>' is missing the following properties from type 'Application<{ 'messages': Message; }>': search, connect, init, defaultConfiguration, and 39 more.`
![image](https://user-images.githubusercontent.com/22234867/59264688-413c2100-8c76-11e9-9a2b-93bd4c9dbf3e.png)

### System configuration

**Module versions** Default generated by cli

**NodeJS version**: 10.16.0

**Operating System**:  Windows 10

**Browser Version**: Not relevant

**React Native Version**: Not relevant

**Module Loader**: npm V 6.9.0

Let me know if I'm doing something wrong.

Thanks for your help and time.

**Comment by pzach01** [comment]
I have the same issue, same system configuration. I am using git bash per https://generator.feathers-plus.com/get-started/

**Comment by Artaud** [comment]
I am getting exactly the same on Ubuntu 18.04, using npm.

**Comment by iva2k** [comment]
I narrowed down the issue to a change in 
node_modules/@types/express-serve-static-core/index.d.ts@4.16.6, this code is **removed** compared to  4.16.0:
```js
export interface Application extends EventEmitter, IRouter, Express.Application {
    ...
    /**
     * Configure callback for zero or more envs,
     * when no `env` is specified that callback will
     * be invoked for all environments. Any combination
     * can be used multiple times, in any order desired.
     *
     * Examples:
     *
     *    app.configure(function(){
     *      // executed for all envs
     *    });
     *
     *    app.configure('stage', function(){
     *      // executed staging env
     *    });
     *
     *    app.configure('stage', 'production', function(){
     *      // executed for stage and production
     *    });
     *
     * Note:
     *
     *  These callbacks are invoked immediately, and
     *  are effectively sugar for the following:
     *
     *     var env = process.env.NODE_ENV || 'development';
     *
     *      switch (env) {
     *        case 'development':
     *          ...
     *          break;
     *        case 'stage':
     *          ...
     *          break;
     *        case 'production':
     *          ...
     *          break;
     *      }
     */
    configure(fn: Function): Application;
    configure(env0: string, fn: Function): Application;
    configure(env0: string, env1: string, fn: Function): Application;
    configure(env0: string, env1: string, env2: string, fn: Function): Application;
    configure(env0: string, env1: string, env2: string, env3: string, fn: Function): Application;
    configure(env0: string, env1: string, env2: string, env3: string, env4: string, fn: Function): Application;
```

To see the effect, add older version of the package:
```bash
npm i -D @types/express-serve-static-core@4.16.0
```

It makes the error go away, log.start:
```
> feathers-app@0.0.0 start C:\dev\feathers-app
> ts-node --files src/

info: Feathers application started on http://localhost:3030
```

By no means it is a true fix, just a workaround, as it merely plugs the type discrepancy with some unrelated function signatures.

**Comment by Navino16** [comment]
Thanks @iva2k ! I will definetly look at this "fix" when I have time if there is no official fix.

**Comment by Artaud** [comment]
I can confirm that this workaround @iva2k suggested worked for me.

**Comment by Ticore** [comment]
update `/src/app.interface.ts` could fix it

```diff
-import { Application } from '@feathersjs/express';
+import { Application } from '@feathersjs/feathers';
```

**Comment by jd4ever** [comment]
@Ticore Thank you. It worked for me!

**Comment by iva2k** [comment]
@Ticore Your fix is the proper way for doing it. Removes bunch of other TypeScript issues down the road as well. 
This fix should be rolled into the generator IMHO.

**Comment by khuongduybui** [comment]
This does not work for me because when I add multi-part upload according to official guide [here](https://docs.feathersjs.com/cookbook/express/file-uploading.html#feathers-blob-with-multipart-support), I am calling `app.use(path, ...handlers, opts?)` signature from `@feathers/express`, not `app.use(path, handler, opts?)` signature from `@feathers/feathers`.

**Comment by Artaud** [comment]
I had the same issues as @khuongduybui and attempted his workaround, only to be greeted by a third error in sequelize.
What worked, surprisingly, was switching the BaseApplication and Application imports, ie.
    import { Application as BaseApplication } from '@feathersjs/express';
    import { Application } from '@feathersjs/feathers';

**Comment by khuongduybui** [comment]
Unfortunately this project seems no longer active. Thanks for posting the workaround anyway.
