### ISSUE TITLE
Upgrade to FeathersJS v4 (Crow)?

### ISSUE THREAD

**Issue by khuongduybui** [feathers-plus/generator-feathers-plus#279]
FeathersJS v4 (Crow) has been released.
https://blog.feathersjs.com/introducing-feathers-4-a-framework-for-real-time-apps-and-rest-apis-afff3819055b

The migration guide is here:
https://docs.feathersjs.com/guides/migrating.html

**Comment by blackholegalaxy** [comment]
@eddyystop  any plan on that?

**Comment by khuongduybui** [comment]
I tried https://docs.feathersjs.com/guides/migrating.html#auto-upgrade but of course that didn't work.

```
➜ feathers upgrade
events.js:170
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/duybui/code/skeleton/api/src/authentication.js
```

It failed to find `authentication.js` because I'm using TypeScript...
On top of that It failed with the same error when trying to upgrade a TypeScript app freshly created from `feathers/cli` too...
I'll try the manual upgrade guide and report later...

**Comment by florianbepunkt** [comment]
Some information on the status/plans for this project from the maintainers would be great.

**Comment by hybridmuse** [comment]
@eddyystop hasn't been active on Github for almost a year now. Hopefully everything's alright for them.

**Comment by guzz** [comment]
I have been making my own generator based on this, and I will have to update to feathers 4 for it, I probably can make a PR for this.
