### ISSUE TITLE
TypeScript compilation error after adding the first service - service x.validate has not exported member 'create'

### ISSUE THREAD

**Issue by triplonetienne** [feathers-plus/generator-feathers-plus#37]
### Steps to reproduce
- Create a configuration with `feathers-plus generate options` selecting TypeScript and semicolon enabled
- Generate the app with `feathers-plus generate app`, all options to default
- Start the empty application (this works): `npm start`
- Stop the application
- Add a new service called 'messages' with `feathers-plus generate service`, all options to default
- Start the application with `npm start` and the TypeScript compilation error is shown

### Expected behavior
I expected that Feathers was started without any problems

### Actual behavior
An TypeScript compilation error occurred:
```
TSError: ⨯ Unable to compile TypeScript:
src/services/messages/messages.hooks.ts(11,10): error TS2305: Module '"[full path]/src/services/messages/messages.validate"' has no exported member 'create'.
src/services/messages/messages.hooks.ts(11,18): error TS2305: Module '"/[full path]/src/services/messages/messages.validate"' has no exported member 'update'.
src/services/messages/messages.hooks.ts(11,26): error TS2305: Module '"[full path]/src/services/messages/messages.validate"' has no exported member 'patch'.
src/services/messages/messages.hooks.ts(11,33): error TS2305: Module '"[full path]/src/services/messages/messages.validate"' has no exported member 'validateCreate'.
src/services/messages/messages.hooks.ts(11,49): error TS2305: Module '"/[full path]/src/services/messages/messages.validate"' has no exported member 'validateUpdate'.
src/services/messages/messages.hooks.ts(11,65): error TS2305: Module '"[full path]/src/services/messages/messages.validate"' has no exported member 'validatePatch'.
```

After commenting out the `import { create, update, patch, validateCreate, validateUpdate, validatePatch } from './messages.validate';` line in messages.hooks.ts, the application starts without any problems.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
"dependencies": {
    "@feathersjs/authentication": "^2.1.7",
    "@feathersjs/authentication-jwt": "^2.0.1",
    "@feathersjs/authentication-local": "^1.2.1",
    "@feathersjs/configuration": "^2.0.2",
    "@feathersjs/errors": "^3.3.2",
    "@feathersjs/express": "^1.2.5",
    "@feathersjs/feathers": "^3.2.1",
    "@feathersjs/socketio": "^3.2.4",
    "ajv": "^5.5.2",
    "compression": "^1.7.3",
    "cors": "^2.8.4",
    "feathers-hooks-common": "^4.16.3",
    "feathers-nedb": "^3.1.0",
    "helmet": "^3.13.0",
    "lodash.merge": "^4.6.1",
    "nedb": "^1.8.0",
    "serve-favicon": "^2.5.0",
    "winston": "^3.0.0"
  },
  "devDependencies": {
    "@types/compression": "0.0.36",
    "@types/cors": "^2.8.4",
    "@types/feathersjs__authentication": "^2.1.1",
    "@types/feathersjs__authentication-jwt": "^1.0.3",
    "@types/feathersjs__authentication-local": "^1.0.2",
    "@types/feathersjs__configuration": "^1.0.1",
    "@types/feathersjs__errors": "^3.2.1",
    "@types/feathersjs__express": "^1.1.4",
    "@types/feathersjs__feathers": "^3.0.4",
    "@types/feathersjs__socketio": "^3.0.3",
    "@types/helmet": "0.0.40",
    "@types/lodash.merge": "^4.6.4",
    "@types/mocha": "^5.2.5",
    "@types/nedb": "^1.8.5",
    "@types/request-promise": "^4.1.42",
    "@types/serve-favicon": "^2.2.30",
    "@types/winston": "^2.4.4",
    "eslint": "^5.5.0",
    "mocha": "^5.2.0",
    "request": "^2.88.0",
    "request-promise": "^4.2.2",
    "ts-mocha": "^2.0.0",
    "ts-node": "^7.0.1",
    "ts-node-dev": "^1.0.0-pre.28",
    "tslint": "^5.11.0",
    "typescript": "^3.0.3"
  }
```

**NodeJS version**: `v8.11.2`

**Operating System**: macOS 10.13.5

**Browser Version**: 

**React Native Version**:

**Module Loader**: TypeScript 3.0.3 with ts-node 7.0.1

**Comment by eddyystop** [comment]
Darn. Thanks for pointing this out.

j2L3e: I added the import from serviceName.validate.?s recently. Nothing refers to the "imported" values. It works for JS but not for TS.

f+/cli has been updated to generate that line commented out. We'll fix it in the next day or two.

Published as f+/cli v0.7.21 using generator v0.6.20.

**Comment by j2L4e** [comment]
The issue is TypeScript's `export default` being compiled to `module.exports.default =`.
Keeping the exports unchanged this would work:
`import validate from 'service.validate.ts'` and then destructure with `const {...} = validate;`

**Comment by j2L4e** [comment]
The TS way would be named exports, but that would need a lot more changes

**Comment by eddyystop** [comment]
Do either of you know if we would have the same problem when we eventually convert to JS modules, that is, are the JS module standard and TS compatible on this?

It would be nice for people to go `import { validateCreate } from '...'` and if we wanted that, this would be the time to allow it.

So the alternative is
```js
module.exports.create = create;
module.exports.update = update;
// ...
```

**Comment by eddyystop** [comment]
We should consider es6 modules when we make import/export choices, as we;ll have to generate them eventually. Below is some syntax from an article on es6 modules http://2ality.com/2014/09/es6-modules-final.html

This seems similar to the TS syntax @j2L4e suggests above.
```js
//------ myFunc.js ------
export default function () { ... };

//------ main1.js ------
import myFunc from 'myFunc';
myFunc();
```

This is the alterative. We would use `module.exports.create = create`, etc.
```js
//------ lib.js ------
export const sqrt = Math.sqrt;
export function square(x) {
    return x * x;
}
export function diag(x, y) {
    return sqrt(square(x) + square(y));
}

//------ main.js ------
import { square, diag } from 'lib';
console.log(square(11)); // 121
console.log(diag(4, 3)); // 5
```

**Comment by eddyystop** [comment]
I would go for the named exports but for backward compatibility. I assume we can go with 
```js
export default moduleExports;
export const create;
...
export function validateCreate;
...
```
which, although ugly, provides backward compatibility and lets TS use the `import { ... } from` syntax?

**Comment by eddyystop** [comment]
j2L4e's suggestion published as f+/cli v0.7.22 using generator v0.6.21.

**Comment by triplonetienne** [comment]
Thanks for solving this issue so quickly!

I solved the problem myself by exporting the moduleExports object directly like `export { create, .., quickValidate }`, but this doesn't give backward compatibility in js.

(I don't know if reopening this ticket is appropriate, but I appreciate your tools very much and would like to thank you)

**Comment by eddyystop** [comment]
Thanks are always very appreciated.
