### ISSUE TITLE
generate fakes throws if a { type: 'ID" } incorrectly has no foreign key fake.

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#39]
This does not work
```js
    memberIds: {
      type: 'array',
      maxItems: 10,
      items:   { type: 'ID' },
    }
```
but this works
```js
    memberIds: {
      type: 'array',
      maxItems: 10,
      items:   { type: 'ID', faker: { fk: 'users:next' } },
    }
```

**Comment by j2L4e** [comment]
Is there something missing in the first snippet? How would it know which fake data to create?

**Comment by eddyystop** [comment]
Exactly. I should have been more explicit. The first example throws an error. It would be better to log a message and either terminate the process or skip the service.

**Comment by eddyystop** [comment]
No values are generated for type: ID fields with no faker: prop .
