### ISSUE TITLE
schema property oneOf should generate model with appropriate type

### ISSUE THREAD

**Issue by gorango** [feathers-plus/generator-feathers-plus#46]
### Steps to reproduce

Using the following schema snippet:
```javascript
oneOf: [{
  type: {enum: ['text']},
  body: {type: 'string'}
}, {
  type: {enum: ['media']},
  body: {type: 'string'},
  media: {type: 'string'}
}]
```

### Expected behavior

Create model properties with name(s) of key and appropriate type(s) (sequelize ex.):
```javascript
type: {type: DataTypes.ENUM('text', 'media')},
body: {type: DataTypes.TEXT},
```

### Actual behavior

Creates model property with name `oneOf` and type `string` (sequelize ex.):
```javascript
oneOf: {type: DataTypes.TEXT}
```

**Comment by eddyystop** [comment]
Shouldn't you be using the `enum` keyword in the JSON-schema? https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#keywords-for-all-types

**Comment by eddyystop** [comment]
Shouldn't you be using something like
```js
fieldName: { enum: ['text', 'media'] }
```

**Comment by gorango** [comment]
It's an option but this is also a valid json schema property so I feel like it should be supported. Especially when using the validator or when generating swagger docs or fake-data - using `oneOf` is more descriptive and produces more accurate results. 

In the case of fake data, it will generate different rows:
```
{ type: 'text', body: 'Fake body' },
{ type: 'media', body: 'Fake body', media: '//mediaurl.com' }
```

**Comment by eddyystop** [comment]
I'll get around to it, but perhaps you want to submit a PR? The JSON-schema to Mongoose conversion module is straight-forward.

**Comment by eddyystop** [comment]
Consolidated in https://github.com/feathers-plus/generator-feathers-plus/issues/81
