### ISSUE TITLE
id or _id is not pushed to *.interface.ts

### ISSUE THREAD

**Issue by murbanowicz** [feathers-plus/generator-feathers-plus#53]
ID or _id field is not being pushed to the interface file. In my opinon it definitely should.

**Comment by eddyystop** [comment]
@j2L4e ^^^

**Comment by murbanowicz** [comment]
Where is it handled? Maybe I could make quick PR as it looks easy (_id to mongo and mongoose nd id to sequelize). Correct me if I am wrong.

**Comment by eddyystop** [comment]
I await jsl4e's reply whether he thinks it should be done.

**Comment by j2L4e** [comment]
Yes, totally! :+1:

**Comment by eddyystop** [comment]
I'll look into it but its not as easy as it may seem. The JSON-schema has to be DB agnostic and DBs typically use either id or _id. The _id are not always strings.

At present both an id and a _id should be in the JSON-file. An id or _id is hard coded into, say, the name.mongoose.ts.

That does not work for the interface file.

**Comment by eddyystop** [comment]
I'll handle https://github.com/feathers-plus/generator-feathers-plus/issues/54 tomorrow and I suggest that be used in the meantime to add either an id or _id as a custom field.
