### ISSUE TITLE
How to add something to the interface to avoid loosing on re-generation?

### ISSUE THREAD

**Issue by murbanowicz** [feathers-plus/generator-feathers-plus#54]
I need to modify the interface file to reflect e.g. data injected in hooks etc 
but at the moment I do not find the place in the code which would allow to do it with avoiding loosing it at re-generation.
Any advice?

**Comment by eddyystop** [comment]
@j2L4e ^^^

**Comment by eddyystop** [comment]
Does this work?
```js
interface UserBase {
  name: string;
  // ... everything that's generated now
}

export interface User extends UserBase {
  // !code: more // !end
}
```

**Comment by eddyystop** [comment]
Published as f+/cli v0.7.33 using generator v0.6.32

**Comment by eddyystop** [comment]
Follow on issue https://github.com/feathers-plus/generator-feathers-plus/issues/56

**Comment by eddyystop** [comment]
@murbanowicz Hi. I've written an article referencing this issue. You are mentioned in it. Do you want any changes to those references? The draft is at https://medium.com/@eddyystop/keep-your-app-up-to-the-minute-with-feathers-plus-cli-57021f24e548
