### ISSUE TITLE
Const Name are not generated correctly in services index.js file

### ISSUE THREAD

**Issue by Mr-Martinez** [feathers-plus/generator-feathers-plus#58]
### Steps to reproduce

The issue was found to be solved here: https://github.com/feathersjs/feathers/issues/539
However it seems the issue persist when using feathers-plus generate service

1. Create a new service `feathers-plus generate service`

2. When asked what to name the service use camelCase
Example: newServiceMethod

3. Choose custom method, no authentication, yes to GraphQL, leave everything else on defaults.

4. Check index.js inside services, the system has used dashes to seperate the words where the Uppercases were.

Javascript variables using dashes is invalid.

### Expected behavior
I expected it to use the CamelCase words given during the naming of the service inside of the index.js inside the services folder. Like the feathers-plus generate hooks does.

### Actual behavior
It used the dashes instead.

I try to work on it myself, but I dont know how the magic of the cli works.
Hooks has no problem with camelCasing when adding itself to the .hooks js file you specify it too.

**Comment by eddyystop** [comment]
Thanks for catching this.

The generator's tests use names like `name1` and they don't have this problem even though the file names used are like `name-1`.

The problem was introduced when the generator implemented feathersjs/generator-feathers PR #379 with https://github.com/feathers-plus/generator-feathers-plus/commit/fb8cb9d8c1e8cf1223b3cb01d5e71b1c0e601d19

**Comment by eddyystop** [comment]
https://github.com/feathers-plus/generator-feathers-plus/issues/59

**Comment by eddyystop** [comment]
Your issue is fixed in f+/cli v0.7.35 using generator v0.6.34.

Please confirm. Thanks.

**Comment by Mr-Martinez** [comment]
Hello @eddyystop,

I have confirmed that the issue has been resolved.

To learn just a little more about how this cli works in code, which file here contains the code that adds the names onto the service from the cli?

**Comment by eddyystop** [comment]
Thanks for pointing out a phrase I've used so many times is ambiguouses. f+/cli v0.7.36 which uses generator v0.6.35. :(
