### ISSUE TITLE
JSON-schema Range not supported

### ISSUE THREAD

**Issue by samburgers** [feathers-plus/generator-feathers-plus#78]
### Steps to reproduce
`src/services/myservice/myservice.schema.js`
```
properties: {
    // !code: schema_properties
    someCount: {
      type: 'integer',
      min: 2,
      max: 10,
    },
    // !end
},
```

or

```
properties: {
    // !code: schema_properties
    someCount: {
      type: 'integer',
      minimum: 2,
      maximum: 10,
    },
    // !end
},
```

### Expected behavior

Should support JSON-schema Range, https://json-schema.org/understanding-json-schema/reference/numeric.html#range and validate `minumum` and `maximum` for Number/Integer

### Actual behavior
Tell us what happens instead

`myservice.mongoose.js`

```
    someCount: {
      type: Number,
      required: true
    },
```

Am able to successfully POST to `localhost:3030/myservice` with `{ "someCount" : 200 }`. It should return validation error. Thanks!

**Comment by eddyystop** [comment]
I mentioned this to Marshall, another Feathers core maintainer. He's view about the validation hooks is "you can’t make assumptions about where to put them, really."

**Comment by samburgers** [comment]
I didn't make any changes other than i outlined above, and wasn't aware the `servicename.hooks.js` file needed updating for some of the validations but thats great to know.

Worth noting some validations such as `enum` already seem to make it over to the Mongoose schema after `generate all`
ie from my generated `src/services/servicename/servicename.mongoose.js`
```
someProp: {
      type: String,
      enum: [
        "option1",
        "option2",
        "option3"
      ]
    },
```
 do you have a basic example of the correct way to declare validations in the `name.hooks.js` file? Thanks!

**Comment by eddyystop** [comment]
The name.validations.?s module exports various various validations.
```js
let moduleExports = {
  create,
  update,
  patch,
  validateCreate,
  validateUpdate,
  validatePatch,
  quickValidate,
  // !code: moduleExports // !end
};
```
Just include what you need where you need it, e.g.
```js
before: {
  create: [ ..., validateCreate(), ...]
}

I assume you know how to write and wire up hooks, but just in case.

validateSchema hook:
https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#validateschema

Hooks Buzzard version docs:
https://docs.feathersjs.com/guides/chat/processing.html
https://docs.feathersjs.com/api/hooks.html

Hooks Auk version docs:
Starting at https://auk.docs.feathersjs.com/guides/step-by-step/basic-feathers/hooks-middleware.html
