### ISSUE TITLE
Allow dynamically adding a service

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#86]
https://github.com/feathersjs/feathers/issues/545

Can we dynamically add to the GraphQL interface also?

**Comment by nithin-ideas2it** [comment]
Hi @eddyystop 
We are trying to add GraphQL for dynamic service.

As I analyzed Feather GraphQL need 2 main files
1. graphql.schemas.js
2. service.resolvers.js or batchloader.resolvers.js.

Where both files need to exist on lifting the application.

We tried to add GraphQL for dynamic service, we achieved generating graphql.schemas.js but **resolvers.js bit difficult** to generate.where the template is too complex.

I am trying it on how to make it available for runtime service.

Any help, Any suggest???

**Comment by eddyystop** [comment]
As I mentioned in our extended chat talks on this, this a generic GraphQL question more than a cli+ question. I did create this issue #86 as a result of that talk just as a reminder to myself.

This is the first thing I would try:
- the resolvers are in name/service.resolvers.js or name/batchloaders.resolvers.js.
- when a program runs `const myResolvers = require(...)` for that module they get an object containing the resolvers.
- I would have the program trying to add resolvers, require that module and merge in JS functions containing the new functions, e.g. `lodash.merge(myResolvers, myAdditionalResolvers)`
- I would *think* any other modules which already required myResolvers would now see the added functions.
- How to create those functions to add in? How to have access to `app`? Do you want access to the utility routines? They'll need them in their own closure. This will be the harder part.

I can't write code and test it out for you because this request is beyound normal support.

**Comment by nithin-ideas2it** [comment]
Thank you @eddyystop for your suggestions sure it will help. Let me try to explore.

**Comment by eddyystop** [comment]
I'd appreciate knowing the results. Thanks.

**Comment by bitflower** [comment]
Hey guys, I'm starting out with GraphQL. I have dynamic services up and running as well. If I find out something new I'll post here.
